/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CreateRouteImport } from './routes/create'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as BookBookIdIndexRouteImport } from './routes/book.$bookId.index'
import { Route as ApiPublicArtSplatRouteImport } from './routes/api/public/art/$'
import { Route as BookBookIdChapterNIndexRouteImport } from './routes/book.$bookId.chapter.$n.index'

const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const BookBookIdIndexRoute = BookBookIdIndexRouteImport.update({
  id: '/book/$bookId/',
  path: '/book/$bookId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicArtSplatRoute = ApiPublicArtSplatRouteImport.update({
  id: '/api/public/art/$',
  path: '/api/public/art/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BookBookIdChapterNIndexRoute = BookBookIdChapterNIndexRouteImport.update({
  id: '/book/$bookId/chapter/$n/',
  path: '/book/$bookId/chapter/$n/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/api/tts': typeof ApiTtsRoute
  '/book/$bookId/': typeof BookBookIdIndexRoute
  '/api/public/art/$': typeof ApiPublicArtSplatRoute
  '/book/$bookId/chapter/$n/': typeof BookBookIdChapterNIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/api/tts': typeof ApiTtsRoute
  '/book/$bookId': typeof BookBookIdIndexRoute
  '/api/public/art/$': typeof ApiPublicArtSplatRoute
  '/book/$bookId/chapter/$n': typeof BookBookIdChapterNIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/api/tts': typeof ApiTtsRoute
  '/book/$bookId/': typeof BookBookIdIndexRoute
  '/api/public/art/$': typeof ApiPublicArtSplatRoute
  '/book/$bookId/chapter/$n/': typeof BookBookIdChapterNIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create'
    | '/api/tts'
    | '/book/$bookId/'
    | '/api/public/art/$'
    | '/book/$bookId/chapter/$n/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create'
    | '/api/tts'
    | '/book/$bookId'
    | '/api/public/art/$'
    | '/book/$bookId/chapter/$n'
  id:
    | '__root__'
    | '/'
    | '/create'
    | '/api/tts'
    | '/book/$bookId/'
    | '/api/public/art/$'
    | '/book/$bookId/chapter/$n/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRoute: typeof CreateRoute
  ApiTtsRoute: typeof ApiTtsRoute
  BookBookIdIndexRoute: typeof BookBookIdIndexRoute
  ApiPublicArtSplatRoute: typeof ApiPublicArtSplatRoute
  BookBookIdChapterNIndexRoute: typeof BookBookIdChapterNIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$bookId/': {
      id: '/book/$bookId/'
      path: '/book/$bookId'
      fullPath: '/book/$bookId/'
      preLoaderRoute: typeof BookBookIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/art/$': {
      id: '/api/public/art/$'
      path: '/api/public/art/$'
      fullPath: '/api/public/art/$'
      preLoaderRoute: typeof ApiPublicArtSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$bookId/chapter/$n/': {
      id: '/book/$bookId/chapter/$n/'
      path: '/book/$bookId/chapter/$n'
      fullPath: '/book/$bookId/chapter/$n/'
      preLoaderRoute: typeof BookBookIdChapterNIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoute: CreateRoute,
  ApiTtsRoute: ApiTtsRoute,
  BookBookIdIndexRoute: BookBookIdIndexRoute,
  ApiPublicArtSplatRoute: ApiPublicArtSplatRoute,
  BookBookIdChapterNIndexRoute: BookBookIdChapterNIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
