/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as CreateRouteImport } from './routes/create'
import { Route as CharacterRouteImport } from './routes/character'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DevSpriteGridRouteImport } from './routes/dev.sprite-grid'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as BookBookIdIndexRouteImport } from './routes/book.$bookId.index'
import { Route as BookBookIdVocabRouteImport } from './routes/book.$bookId.vocab'
import { Route as BookBookIdProgressRouteImport } from './routes/book.$bookId.progress'
import { Route as ApiPublicArtSplatRouteImport } from './routes/api/public/art/$'
import { Route as BookBookIdChapterNIndexRouteImport } from './routes/book.$bookId.chapter.$n.index'
import { Route as BookBookIdChapterNQuizRouteImport } from './routes/book.$bookId.chapter.$n.quiz'

const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const CharacterRoute = CharacterRouteImport.update({
  id: '/character',
  path: '/character',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevSpriteGridRoute = DevSpriteGridRouteImport.update({
  id: '/dev/sprite-grid',
  path: '/dev/sprite-grid',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const BookBookIdIndexRoute = BookBookIdIndexRouteImport.update({
  id: '/book/$bookId/',
  path: '/book/$bookId/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookBookIdVocabRoute = BookBookIdVocabRouteImport.update({
  id: '/book/$bookId/vocab',
  path: '/book/$bookId/vocab',
  getParentRoute: () => rootRouteImport,
} as any)
const BookBookIdProgressRoute = BookBookIdProgressRouteImport.update({
  id: '/book/$bookId/progress',
  path: '/book/$bookId/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicArtSplatRoute = ApiPublicArtSplatRouteImport.update({
  id: '/api/public/art/$',
  path: '/api/public/art/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BookBookIdChapterNIndexRoute = BookBookIdChapterNIndexRouteImport.update({
  id: '/book/$bookId/chapter/$n/',
  path: '/book/$bookId/chapter/$n/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookBookIdChapterNQuizRoute = BookBookIdChapterNQuizRouteImport.update({
  id: '/book/$bookId/chapter/$n/quiz',
  path: '/book/$bookId/chapter/$n/quiz',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/character': typeof CharacterRoute
  '/create': typeof CreateRoute
  '/shop': typeof ShopRoute
  '/api/tts': typeof ApiTtsRoute
  '/dev/sprite-grid': typeof DevSpriteGridRoute
  '/book/$bookId/progress': typeof BookBookIdProgressRoute
  '/book/$bookId/vocab': typeof BookBookIdVocabRoute
  '/book/$bookId/': typeof BookBookIdIndexRoute
  '/api/public/art/$': typeof ApiPublicArtSplatRoute
  '/book/$bookId/chapter/$n/quiz': typeof BookBookIdChapterNQuizRoute
  '/book/$bookId/chapter/$n/': typeof BookBookIdChapterNIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/character': typeof CharacterRoute
  '/create': typeof CreateRoute
  '/shop': typeof ShopRoute
  '/api/tts': typeof ApiTtsRoute
  '/dev/sprite-grid': typeof DevSpriteGridRoute
  '/book/$bookId/progress': typeof BookBookIdProgressRoute
  '/book/$bookId/vocab': typeof BookBookIdVocabRoute
  '/book/$bookId': typeof BookBookIdIndexRoute
  '/api/public/art/$': typeof ApiPublicArtSplatRoute
  '/book/$bookId/chapter/$n/quiz': typeof BookBookIdChapterNQuizRoute
  '/book/$bookId/chapter/$n': typeof BookBookIdChapterNIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/character': typeof CharacterRoute
  '/create': typeof CreateRoute
  '/shop': typeof ShopRoute
  '/api/tts': typeof ApiTtsRoute
  '/dev/sprite-grid': typeof DevSpriteGridRoute
  '/book/$bookId/progress': typeof BookBookIdProgressRoute
  '/book/$bookId/vocab': typeof BookBookIdVocabRoute
  '/book/$bookId/': typeof BookBookIdIndexRoute
  '/api/public/art/$': typeof ApiPublicArtSplatRoute
  '/book/$bookId/chapter/$n/quiz': typeof BookBookIdChapterNQuizRoute
  '/book/$bookId/chapter/$n/': typeof BookBookIdChapterNIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/character'
    | '/create'
    | '/shop'
    | '/api/tts'
    | '/dev/sprite-grid'
    | '/book/$bookId/progress'
    | '/book/$bookId/vocab'
    | '/book/$bookId/'
    | '/api/public/art/$'
    | '/book/$bookId/chapter/$n/quiz'
    | '/book/$bookId/chapter/$n/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/character'
    | '/create'
    | '/shop'
    | '/api/tts'
    | '/dev/sprite-grid'
    | '/book/$bookId/progress'
    | '/book/$bookId/vocab'
    | '/book/$bookId'
    | '/api/public/art/$'
    | '/book/$bookId/chapter/$n/quiz'
    | '/book/$bookId/chapter/$n'
  id:
    | '__root__'
    | '/'
    | '/character'
    | '/create'
    | '/shop'
    | '/api/tts'
    | '/dev/sprite-grid'
    | '/book/$bookId/progress'
    | '/book/$bookId/vocab'
    | '/book/$bookId/'
    | '/api/public/art/$'
    | '/book/$bookId/chapter/$n/quiz'
    | '/book/$bookId/chapter/$n/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CharacterRoute: typeof CharacterRoute
  CreateRoute: typeof CreateRoute
  ShopRoute: typeof ShopRoute
  ApiTtsRoute: typeof ApiTtsRoute
  DevSpriteGridRoute: typeof DevSpriteGridRoute
  BookBookIdProgressRoute: typeof BookBookIdProgressRoute
  BookBookIdVocabRoute: typeof BookBookIdVocabRoute
  BookBookIdIndexRoute: typeof BookBookIdIndexRoute
  ApiPublicArtSplatRoute: typeof ApiPublicArtSplatRoute
  BookBookIdChapterNQuizRoute: typeof BookBookIdChapterNQuizRoute
  BookBookIdChapterNIndexRoute: typeof BookBookIdChapterNIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/character': {
      id: '/character'
      path: '/character'
      fullPath: '/character'
      preLoaderRoute: typeof CharacterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/sprite-grid': {
      id: '/dev/sprite-grid'
      path: '/dev/sprite-grid'
      fullPath: '/dev/sprite-grid'
      preLoaderRoute: typeof DevSpriteGridRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$bookId/': {
      id: '/book/$bookId/'
      path: '/book/$bookId'
      fullPath: '/book/$bookId/'
      preLoaderRoute: typeof BookBookIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$bookId/vocab': {
      id: '/book/$bookId/vocab'
      path: '/book/$bookId/vocab'
      fullPath: '/book/$bookId/vocab'
      preLoaderRoute: typeof BookBookIdVocabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$bookId/progress': {
      id: '/book/$bookId/progress'
      path: '/book/$bookId/progress'
      fullPath: '/book/$bookId/progress'
      preLoaderRoute: typeof BookBookIdProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/art/$': {
      id: '/api/public/art/$'
      path: '/api/public/art/$'
      fullPath: '/api/public/art/$'
      preLoaderRoute: typeof ApiPublicArtSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$bookId/chapter/$n/': {
      id: '/book/$bookId/chapter/$n/'
      path: '/book/$bookId/chapter/$n'
      fullPath: '/book/$bookId/chapter/$n/'
      preLoaderRoute: typeof BookBookIdChapterNIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$bookId/chapter/$n/quiz': {
      id: '/book/$bookId/chapter/$n/quiz'
      path: '/book/$bookId/chapter/$n/quiz'
      fullPath: '/book/$bookId/chapter/$n/quiz'
      preLoaderRoute: typeof BookBookIdChapterNQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CharacterRoute: CharacterRoute,
  CreateRoute: CreateRoute,
  ShopRoute: ShopRoute,
  ApiTtsRoute: ApiTtsRoute,
  DevSpriteGridRoute: DevSpriteGridRoute,
  BookBookIdProgressRoute: BookBookIdProgressRoute,
  BookBookIdVocabRoute: BookBookIdVocabRoute,
  BookBookIdIndexRoute: BookBookIdIndexRoute,
  ApiPublicArtSplatRoute: ApiPublicArtSplatRoute,
  BookBookIdChapterNQuizRoute: BookBookIdChapterNQuizRoute,
  BookBookIdChapterNIndexRoute: BookBookIdChapterNIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
